export const BEACH_RADAR_BOMB_FRAMES = 360;

export type BombVariant = {
  id: string;
  name: string;
  hookTop: string;
  hookBottom: string;
  subline: string;
  valueTitle: string;
  valueSub: string;
  ctaTitle: string;
  ctaLead: string;
  ctaButton: string;
  accent: string;
  accentSoft: string;
  introStyle: 1 | 2 | 3 | 4 | 5;
  valueStyle: 1 | 2 | 3 | 4 | 5;
  ctaStyle: 1 | 2 | 3 | 4 | 5;
  hue: number;
  saturation: number;
  darkness: number;
};

export const BEACH_RADAR_BOMB_VARIANTS: BombVariant[] = [
  {
    id: "01",
    name: "Variazione 01",
    hookTop: "EVITA LA FOLLA.",
    hookBottom: "MUOVITI MEGLIO.",
    subline: "Controlla le spiagge in tempo reale.",
    valueTitle: "SITUAZIONE IMMEDIATA",
    valueSub: "Le segnalazioni aiutano a decidere subito.",
    ctaTitle: "Beach Radar sta arrivando.",
    ctaLead: "ISCRIVITI ALLA LISTA D'ATTESA",
    ctaButton: "ISCRIVITI ORA",
    accent: "#06B6D4",
    accentSoft: "rgba(6,182,212,0.28)",
    introStyle: 1,
    valueStyle: 1,
    ctaStyle: 1,
    hue: 0,
    saturation: 1.12,
    darkness: 0.62,
  },
  {
    id: "02",
    name: "Variazione 02",
    hookTop: "MENO CONFUSIONE.",
    hookBottom: "PIU TEMPO AL MARE.",
    subline: "Apri la mappa e trova la zona giusta.",
    valueTitle: "DOVE C'E SPAZIO",
    valueSub: "Un colpo d'occhio e parti.",
    ctaTitle: "Le nuove mappe sono in arrivo.",
    ctaLead: "ENTRA NELLA LISTA D'ATTESA",
    ctaButton: "ISCRIVITI ORA",
    accent: "#22D3EE",
    accentSoft: "rgba(34,211,238,0.26)",
    introStyle: 2,
    valueStyle: 2,
    ctaStyle: 2,
    hue: 10,
    saturation: 1.08,
    darkness: 0.56,
  },
  {
    id: "03",
    name: "Variazione 03",
    hookTop: "GUARDA PRIMA.",
    hookBottom: "SCEGLI MEGLIO.",
    subline: "La comunita segnala in tempo reale.",
    valueTitle: "SEGNALI CONTINUI",
    valueSub: "Aggiornamenti chiari durante la giornata.",
    ctaTitle: "Tutto pronto per il lancio.",
    ctaLead: "LASCIA LA TUA ISCRIZIONE",
    ctaButton: "VAI ALLA LISTA D'ATTESA",
    accent: "#0EA5E9",
    accentSoft: "rgba(14,165,233,0.3)",
    introStyle: 3,
    valueStyle: 3,
    ctaStyle: 3,
    hue: -8,
    saturation: 1.2,
    darkness: 0.58,
  },
  {
    id: "04",
    name: "Variazione 04",
    hookTop: "NIENTE CAOS.",
    hookBottom: "SCELTE CHIARE.",
    subline: "Beach Radar rende semplice decidere.",
    valueTitle: "DATI UTILI SUBITO",
    valueSub: "Ogni zona con uno stato chiaro.",
    ctaTitle: "Il servizio apre presto.",
    ctaLead: "ISCRIVITI PER RESTARE AGGIORNATO",
    ctaButton: "ISCRIVITI ORA",
    accent: "#38BDF8",
    accentSoft: "rgba(56,189,248,0.3)",
    introStyle: 4,
    valueStyle: 4,
    ctaStyle: 4,
    hue: 14,
    saturation: 1.06,
    darkness: 0.54,
  },
  {
    id: "05",
    name: "Variazione 05",
    hookTop: "ARRIVA PRIMA.",
    hookBottom: "GODITI IL MARE.",
    subline: "Sai dove andare prima di partire.",
    valueTitle: "PANORAMICA COMPLETA",
    valueSub: "Mappa chiara e segnali costanti.",
    ctaTitle: "Manca poco all'apertura.",
    ctaLead: "METTITI IN LISTA D'ATTESA",
    ctaButton: "INVIAMI L'AVVISO",
    accent: "#2DD4BF",
    accentSoft: "rgba(45,212,191,0.3)",
    introStyle: 5,
    valueStyle: 5,
    ctaStyle: 5,
    hue: -14,
    saturation: 1.14,
    darkness: 0.64,
  },
  {
    id: "06",
    name: "Variazione 06",
    hookTop: "SCANSIONA.",
    hookBottom: "SCEGLI.",
    subline: "Le spiagge cambiano, la mappa si aggiorna.",
    valueTitle: "AGGIORNAMENTI COSTANTI",
    valueSub: "Informazioni pratiche in pochi secondi.",
    ctaTitle: "Beach Radar arriva a breve.",
    ctaLead: "REGISTRATI ALLA LISTA D'ATTESA",
    ctaButton: "ISCRIVITI SUBITO",
    accent: "#22D3EE",
    accentSoft: "rgba(34,211,238,0.25)",
    introStyle: 1,
    valueStyle: 3,
    ctaStyle: 4,
    hue: 20,
    saturation: 1.1,
    darkness: 0.57,
  },
  {
    id: "07",
    name: "Variazione 07",
    hookTop: "MENO STRESS.",
    hookBottom: "PIU MARE.",
    subline: "Trova la zona migliore senza perdere tempo.",
    valueTitle: "AFFOLLAMENTO CHIARO",
    valueSub: "Confronta zone in un attimo.",
    ctaTitle: "Stiamo per partire.",
    ctaLead: "INSERISCI LA TUA ISCRIZIONE",
    ctaButton: "ENTRA IN LISTA",
    accent: "#06B6D4",
    accentSoft: "rgba(6,182,212,0.3)",
    introStyle: 2,
    valueStyle: 4,
    ctaStyle: 1,
    hue: -4,
    saturation: 1.16,
    darkness: 0.6,
  },
  {
    id: "08",
    name: "Variazione 08",
    hookTop: "SEGUI LA SITUAZIONE.",
    hookBottom: "BATTI LA FOLLA.",
    subline: "Le segnalazioni della comunita fanno la differenza.",
    valueTitle: "TRACCIA LA GIORNATA",
    valueSub: "Dove andare ora, senza tentativi.",
    ctaTitle: "Nuove segnalazioni in arrivo.",
    ctaLead: "ISCRIVITI ALLA LISTA D'ATTESA",
    ctaButton: "MI ISCRIVO ORA",
    accent: "#0EA5E9",
    accentSoft: "rgba(14,165,233,0.26)",
    introStyle: 3,
    valueStyle: 5,
    ctaStyle: 2,
    hue: 6,
    saturation: 1.1,
    darkness: 0.59,
  },
  {
    id: "09",
    name: "Variazione 09",
    hookTop: "NON INDOVINARE.",
    hookBottom: "VERIFICA.",
    subline: "Uno sguardo e sai gia dove andare.",
    valueTitle: "RISPOSTA RAPIDA",
    valueSub: "Tre segnali, una decisione.",
    ctaTitle: "Il lancio e vicino.",
    ctaLead: "ENTRA NELLA LISTA D'ATTESA",
    ctaButton: "ISCRIVIMI",
    accent: "#06B6D4",
    accentSoft: "rgba(6,182,212,0.27)",
    introStyle: 4,
    valueStyle: 1,
    ctaStyle: 3,
    hue: -16,
    saturation: 1.12,
    darkness: 0.61,
  },
  {
    id: "10",
    name: "Variazione 10",
    hookTop: "PRIMA IL RADAR.",
    hookBottom: "POI LA PARTENZA.",
    subline: "Aggiornamenti reali, zero rumore.",
    valueTitle: "SEGNALAZIONI CHIARE",
    valueSub: "Recente e previsione sullo stesso piano.",
    ctaTitle: "Apertura imminente.",
    ctaLead: "REGISTRATI ALLA LISTA D'ATTESA",
    ctaButton: "ISCRIVITI ADESSO",
    accent: "#22D3EE",
    accentSoft: "rgba(34,211,238,0.29)",
    introStyle: 5,
    valueStyle: 2,
    ctaStyle: 4,
    hue: 12,
    saturation: 1.06,
    darkness: 0.55,
  },
  {
    id: "11",
    name: "Variazione 11",
    hookTop: "TUTTO SOTTO CONTROLLO.",
    hookBottom: "IN TEMPO REALE.",
    subline: "Il tuo radar per la spiaggia migliore.",
    valueTitle: "MENO ATTESA",
    valueSub: "Piu tempo nel posto giusto.",
    ctaTitle: "Beach Radar arriva presto.",
    ctaLead: "LASCIA LA TUA ISCRIZIONE",
    ctaButton: "ENTRA ORA",
    accent: "#06B6D4",
    accentSoft: "rgba(6,182,212,0.3)",
    introStyle: 1,
    valueStyle: 4,
    ctaStyle: 5,
    hue: -2,
    saturation: 1.18,
    darkness: 0.63,
  },
  {
    id: "12",
    name: "Variazione 12",
    hookTop: "SPAZIO LIBERO.",
    hookBottom: "SCELTA IMMEDIATA.",
    subline: "Beach Radar ordina il caos per te.",
    valueTitle: "CONTROLLO RAPIDO",
    valueSub: "Situazione aggiornata, subito.",
    ctaTitle: "Stiamo ultimando il lancio.",
    ctaLead: "ISCRIVITI ALLA LISTA D'ATTESA",
    ctaButton: "VOGLIO PARTECIPARE",
    accent: "#22D3EE",
    accentSoft: "rgba(34,211,238,0.28)",
    introStyle: 2,
    valueStyle: 5,
    ctaStyle: 3,
    hue: 18,
    saturation: 1.04,
    darkness: 0.53,
  },
  {
    id: "13",
    name: "Variazione 13",
    hookTop: "VAI SUL SICURO.",
    hookBottom: "OGNI VOLTA.",
    subline: "Segnali forti, lettura semplice.",
    valueTitle: "ZERO CONFUSIONE",
    valueSub: "Solo quello che serve decidere.",
    ctaTitle: "Nuovo servizio in arrivo.",
    ctaLead: "METTITI IN LISTA D'ATTESA",
    ctaButton: "RICEVI L'AVVISO",
    accent: "#14B8A6",
    accentSoft: "rgba(20,184,166,0.3)",
    introStyle: 3,
    valueStyle: 1,
    ctaStyle: 2,
    hue: -10,
    saturation: 1.13,
    darkness: 0.6,
  },
  {
    id: "14",
    name: "Variazione 14",
    hookTop: "SALTA LE FILE.",
    hookBottom: "PRENDI LA STRADA GIUSTA.",
    subline: "Un radar pratico per giornate perfette.",
    valueTitle: "DOVE CONVIENE ADESSO",
    valueSub: "Community attiva, mappa utile.",
    ctaTitle: "Apertura sempre piu vicina.",
    ctaLead: "ISCRIVITI ORA",
    ctaButton: "ENTRA NELLA LISTA",
    accent: "#0EA5E9",
    accentSoft: "rgba(14,165,233,0.28)",
    introStyle: 4,
    valueStyle: 2,
    ctaStyle: 5,
    hue: 4,
    saturation: 1.08,
    darkness: 0.56,
  },
  {
    id: "15",
    name: "Variazione 15",
    hookTop: "IL RADAR DELLE SPIAGGE.",
    hookBottom: "PRONTO QUANDO SERVE.",
    subline: "Dati della comunita, scelta immediata.",
    valueTitle: "TRE STATI, UNA RISPOSTA",
    valueSub: "Situazione attuale, recente e prevista.",
    ctaTitle: "Beach Radar sta per partire.",
    ctaLead: "ISCRIVITI ALLA LISTA D'ATTESA",
    ctaButton: "RICHIEDI IL PROMEMORIA",
    accent: "#06B6D4",
    accentSoft: "rgba(6,182,212,0.3)",
    introStyle: 5,
    valueStyle: 3,
    ctaStyle: 1,
    hue: -6,
    saturation: 1.16,
    darkness: 0.62,
  },
];
