export const BEACH_RADAR_BOMB_FRAMES = 360;

export type BombVariant = {
  id: string;
  name: string;
  hookTop: string;
  hookBottom: string;
  subline: string;
  valueTitle: string;
  valueSub: string;
  ctaTitle: string;
  ctaLead: string;
  ctaButton: string;
  accent: string;
  accentSoft: string;
  introStyle: 1 | 2 | 3 | 4 | 5;
  valueStyle: 1 | 2 | 3 | 4 | 5;
  ctaStyle: 1 | 2 | 3 | 4 | 5;
  hue: number;
  saturation: number;
  darkness: number;
};

export const BEACH_RADAR_BOMB_VARIANTS: BombVariant[] = [
  {
    id: "01",
    name: "Variazione 01",
    hookTop: "EVITA LA FOLLA.",
    hookBottom: "MUOVITI MEGLIO.",
    subline: "Controlla le spiagge in tempo reale.",
    valueTitle: "SITUAZIONE IMMEDIATA",
    valueSub: "Le segnalazioni aiutano a decidere subito.",
    ctaTitle: "Where2Beach sta arrivando.",
    ctaLead: "ISCRIVITI ALLA LISTA D'ATTESA",
    ctaButton: "ISCRIVITI ORA",
    accent: "#06B6D4",
    accentSoft: "rgba(6,182,212,0.28)",
    introStyle: 1,
    valueStyle: 1,
    ctaStyle: 1,
    hue: 0,
    saturation: 1.12,
    darkness: 0.62,
  },
  {
    id: "02",
    name: "Variazione 02",
    hookTop: "MENO CONFUSIONE.",
    hookBottom: "PIU TEMPO AL MARE.",
    subline: "Apri la mappa e trova la zona giusta.",
    valueTitle: "DOVE C'E SPAZIO",
    valueSub: "Un colpo d'occhio e parti.",
    ctaTitle: "Le nuove mappe sono in arrivo.",
    ctaLead: "ENTRA NELLA LISTA D'ATTESA",
    ctaButton: "ISCRIVITI ORA",
    accent: "#22D3EE",
    accentSoft: "rgba(34,211,238,0.26)",
    introStyle: 2,
    valueStyle: 2,
    ctaStyle: 2,
    hue: 10,
    saturation: 1.08,
    darkness: 0.56,
  },
  {
    id: "03",
    name: "Variazione 03",
    hookTop: "GUARDA PRIMA.",
    hookBottom: "SCEGLI MEGLIO.",
    subline: "La comunita segnala in tempo reale.",
    valueTitle: "SEGNALI CONTINUI",
    valueSub: "Aggiornamenti chiari durante la giornata.",
    ctaTitle: "Tutto pronto per il lancio.",
    ctaLead: "LASCIA LA TUA ISCRIZIONE",
    ctaButton: "VAI ALLA LISTA D'ATTESA",
    accent: "#0EA5E9",
    accentSoft: "rgba(14,165,233,0.3)",
    introStyle: 3,
    valueStyle: 3,
    ctaStyle: 3,
    hue: -8,
    saturation: 1.2,
    darkness: 0.58,
  },
  {
    id: "04",
    name: "Variazione 04",
    hookTop: "NIENTE CAOS.",
    hookBottom: "SCELTE CHIARE.",
    subline: "Where2Beach rende semplice decidere.",
    valueTitle: "DATI UTILI SUBITO",
    valueSub: "Ogni zona con uno stato chiaro.",
    ctaTitle: "Il servizio apre presto.",
    ctaLead: "ISCRIVITI PER RESTARE AGGIORNATO",
    ctaButton: "ISCRIVITI ORA",
    accent: "#38BDF8",
    accentSoft: "rgba(56,189,248,0.3)",
    introStyle: 4,
    valueStyle: 4,
    ctaStyle: 4,
    hue: 14,
    saturation: 1.06,
    darkness: 0.54,
  },
  {
    id: "05",
    name: "Variazione 05",
    hookTop: "ARRIVA PRIMA.",
    hookBottom: "GODITI IL MARE.",
    subline: "Sai dove andare prima di partire.",
    valueTitle: "PANORAMICA COMPLETA",
    valueSub: "Mappa chiara e segnali costanti.",
    ctaTitle: "Manca poco all'apertura.",
    ctaLead: "METTITI IN LISTA D'ATTESA",
    ctaButton: "INVIAMI L'AVVISO",
    accent: "#2DD4BF",
    accentSoft: "rgba(45,212,191,0.3)",
    introStyle: 5,
    valueStyle: 5,
    ctaStyle: 5,
    hue: -14,
    saturation: 1.14,
    darkness: 0.64,
  },
  {
    id: "06",
    name: "Variazione 06",
    hookTop: "SCANSIONA.",
    hookBottom: "SCEGLI.",
    subline: "Le spiagge cambiano, la mappa si aggiorna.",
    valueTitle: "AGGIORNAMENTI COSTANTI",
    valueSub: "Informazioni pratiche in pochi secondi.",
    ctaTitle: "Where2Beach arriva a breve.",
    ctaLead: "REGISTRATI ALLA LISTA D'ATTESA",
    ctaButton: "ISCRIVITI SUBITO",
    accent: "#22D3EE",
    accentSoft: "rgba(34,211,238,0.25)",
    introStyle: 1,
    valueStyle: 3,
    ctaStyle: 4,
    hue: 20,
    saturation: 1.1,
    darkness: 0.57,
  },
  {
    id: "07",
    name: "Variazione 07",
    hookTop: "MENO STRESS.",
    hookBottom: "PIU MARE.",
    subline: "Trova la zona migliore senza perdere tempo.",
    valueTitle: "AFFOLLAMENTO CHIARO",
    valueSub: "Confronta zone in un attimo.",
    ctaTitle: "Stiamo per partire.",
    ctaLead: "INSERISCI LA TUA ISCRIZIONE",
    ctaButton: "ENTRA IN LISTA",
    accent: "#06B6D4",
    accentSoft: "rgba(6,182,212,0.3)",
    introStyle: 2,
    valueStyle: 4,
    ctaStyle: 1,
    hue: -4,
    saturation: 1.16,
    darkness: 0.6,
  },
  {
    id: "08",
    name: "Variazione 08",
    hookTop: "SEGUI LA SITUAZIONE.",
    hookBottom: "BATTI LA FOLLA.",
    subline: "Le segnalazioni della comunita fanno la differenza.",
    valueTitle: "TRACCIA LA GIORNATA",
    valueSub: "Dove andare ora, senza tentativi.",
    ctaTitle: "Nuove segnalazioni in arrivo.",
    ctaLead: "ISCRIVITI ALLA LISTA D'ATTESA",
    ctaButton: "MI ISCRIVO ORA",
    accent: "#0EA5E9",
    accentSoft: "rgba(14,165,233,0.26)",
    introStyle: 3,
    valueStyle: 5,
    ctaStyle: 2,
    hue: 6,
    saturation: 1.1,
    darkness: 0.59,
  },
  {
    id: "09",
    name: "Variazione 09",
    hookTop: "NON INDOVINARE.",
    hookBottom: "VERIFICA.",
    subline: "Uno sguardo e sai gia dove andare.",
    valueTitle: "RISPOSTA RAPIDA",
    valueSub: "Tre segnali, una decisione.",
    ctaTitle: "Il lancio e vicino.",
    ctaLead: "ENTRA NELLA LISTA D'ATTESA",
    ctaButton: "ISCRIVIMI",
    accent: "#06B6D4",
    accentSoft: "rgba(6,182,212,0.27)",
    introStyle: 4,
    valueStyle: 1,
    ctaStyle: 3,
    hue: -16,
    saturation: 1.12,
    darkness: 0.61,
  },
  {
    id: "10",
    name: "Variazione 10",
    hookTop: "PRIMA IL RADAR.",
    hookBottom: "POI LA PARTENZA.",
    subline: "Aggiornamenti reali, zero rumore.",
    valueTitle: "SEGNALAZIONI CHIARE",
    valueSub: "Recente e previsione sullo stesso piano.",
    ctaTitle: "Apertura imminente.",
    ctaLead: "REGISTRATI ALLA LISTA D'ATTESA",
    ctaButton: "ISCRIVITI ADESSO",
    accent: "#22D3EE",
    accentSoft: "rgba(34,211,238,0.29)",
    introStyle: 5,
    valueStyle: 2,
    ctaStyle: 4,
    hue: 12,
    saturation: 1.06,
    darkness: 0.55,
  },
  {
    id: "11",
    name: "Variazione 11",
    hookTop: "TUTTO SOTTO CONTROLLO.",
    hookBottom: "IN TEMPO REALE.",
    subline: "Il tuo radar per la spiaggia migliore.",
    valueTitle: "MENO ATTESA",
    valueSub: "Piu tempo nel posto giusto.",
    ctaTitle: "Where2Beach arriva presto.",
    ctaLead: "LASCIA LA TUA ISCRIZIONE",
    ctaButton: "ENTRA ORA",
    accent: "#06B6D4",
    accentSoft: "rgba(6,182,212,0.3)",
    introStyle: 1,
    valueStyle: 4,
    ctaStyle: 5,
    hue: -2,
    saturation: 1.18,
    darkness: 0.63,
  },
  {
    id: "12",
    name: "Variazione 12",
    hookTop: "SPAZIO LIBERO.",
    hookBottom: "SCELTA IMMEDIATA.",
    subline: "Where2Beach ordina il caos per te.",
    valueTitle: "CONTROLLO RAPIDO",
    valueSub: "Situazione aggiornata, subito.",
    ctaTitle: "Stiamo ultimando il lancio.",
    ctaLead: "ISCRIVITI ALLA LISTA D'ATTESA",
    ctaButton: "VOGLIO PARTECIPARE",
    accent: "#22D3EE",
    accentSoft: "rgba(34,211,238,0.28)",
    introStyle: 2,
    valueStyle: 5,
    ctaStyle: 3,
    hue: 18,
    saturation: 1.04,
    darkness: 0.53,
  },
  {
    id: "13",
    name: "Variazione 13",
    hookTop: "VAI SUL SICURO.",
    hookBottom: "OGNI VOLTA.",
    subline: "Segnali forti, lettura semplice.",
    valueTitle: "ZERO CONFUSIONE",
    valueSub: "Solo quello che serve decidere.",
    ctaTitle: "Nuovo servizio in arrivo.",
    ctaLead: "METTITI IN LISTA D'ATTESA",
    ctaButton: "RICEVI L'AVVISO",
    accent: "#14B8A6",
    accentSoft: "rgba(20,184,166,0.3)",
    introStyle: 3,
    valueStyle: 1,
    ctaStyle: 2,
    hue: -10,
    saturation: 1.13,
    darkness: 0.6,
  },
  {
    id: "14",
    name: "Variazione 14",
    hookTop: "SALTA LE FILE.",
    hookBottom: "PRENDI LA STRADA GIUSTA.",
    subline: "Un radar pratico per giornate perfette.",
    valueTitle: "DOVE CONVIENE ADESSO",
    valueSub: "Community attiva, mappa utile.",
    ctaTitle: "Apertura sempre piu vicina.",
    ctaLead: "ISCRIVITI ORA",
    ctaButton: "ENTRA NELLA LISTA",
    accent: "#0EA5E9",
    accentSoft: "rgba(14,165,233,0.28)",
    introStyle: 4,
    valueStyle: 2,
    ctaStyle: 5,
    hue: 4,
    saturation: 1.08,
    darkness: 0.56,
  },
  {
    id: "15",
    name: "Variazione 15",
    hookTop: "IL RADAR DELLE SPIAGGE.",
    hookBottom: "PRONTO QUANDO SERVE.",
    subline: "Dati della comunita, scelta immediata.",
    valueTitle: "TRE STATI, UNA RISPOSTA",
    valueSub: "Situazione attuale, recente e prevista.",
    ctaTitle: "Where2Beach sta per partire.",
    ctaLead: "ISCRIVITI ALLA LISTA D'ATTESA",
    ctaButton: "RICHIEDI IL PROMEMORIA",
    accent: "#06B6D4",
    accentSoft: "rgba(6,182,212,0.3)",
    introStyle: 5,
    valueStyle: 3,
    ctaStyle: 1,
    hue: -6,
    saturation: 1.16,
    darkness: 0.62,
  },
  {
    id: "16",
    name: "Variazione 16",
    hookTop: "PIU MARE.",
    hookBottom: "MENO ATTESA.",
    subline: "Apri il radar e scegli la spiaggia giusta.",
    valueTitle: "STATO IN UN ATTIMO",
    valueSub: "Le zone cambiano, tu resti aggiornato.",
    ctaTitle: "Nuova estate, nuove scelte.",
    ctaLead: "ENTRA NELLA LISTA D'ATTESA",
    ctaButton: "ISCRIVITI OGGI",
    accent: "#38BDF8",
    accentSoft: "rgba(56,189,248,0.28)",
    introStyle: 1,
    valueStyle: 2,
    ctaStyle: 3,
    hue: 22,
    saturation: 1.09,
    darkness: 0.58,
  },
  {
    id: "17",
    name: "Variazione 17",
    hookTop: "SEGNALI CHIARI.",
    hookBottom: "ZERO DUBBI.",
    subline: "La community ti aiuta a decidere prima.",
    valueTitle: "SCELTA PIU VELOCE",
    valueSub: "Confronta piu zone in pochi secondi.",
    ctaTitle: "Where2Beach sta per aprire.",
    ctaLead: "REGISTRATI ALLA WAITLIST",
    ctaButton: "VAI IN LISTA",
    accent: "#14B8A6",
    accentSoft: "rgba(20,184,166,0.28)",
    introStyle: 2,
    valueStyle: 3,
    ctaStyle: 4,
    hue: -12,
    saturation: 1.15,
    darkness: 0.61,
  },
  {
    id: "18",
    name: "Variazione 18",
    hookTop: "ANTICIPA LA FOLLA.",
    hookBottom: "MUOVITI PRIMA.",
    subline: "Aggiornamenti continui, scelta immediata.",
    valueTitle: "RADAR IN DIRETTA",
    valueSub: "Sai subito dove conviene andare.",
    ctaTitle: "La mappa che ti serve sta arrivando.",
    ctaLead: "ISCRIVITI ADESSO",
    ctaButton: "MI METTO IN LISTA",
    accent: "#06B6D4",
    accentSoft: "rgba(6,182,212,0.3)",
    introStyle: 3,
    valueStyle: 4,
    ctaStyle: 5,
    hue: 8,
    saturation: 1.07,
    darkness: 0.55,
  },
  {
    id: "19",
    name: "Variazione 19",
    hookTop: "VAI DRITTO.",
    hookBottom: "SENZA GIRARE A VUOTO.",
    subline: "Un check rapido e parti sereno.",
    valueTitle: "MENO CAOS, PIU TEMPO",
    valueSub: "I segnali parlano chiaro durante il giorno.",
    ctaTitle: "Ti avvisiamo al lancio.",
    ctaLead: "LASCIA LA TUA EMAIL",
    ctaButton: "ISCRIVIMI ORA",
    accent: "#22D3EE",
    accentSoft: "rgba(34,211,238,0.3)",
    introStyle: 4,
    valueStyle: 5,
    ctaStyle: 1,
    hue: -18,
    saturation: 1.18,
    darkness: 0.63,
  },
  {
    id: "20",
    name: "Variazione 20",
    hookTop: "IL TUO TEMPO CONTA.",
    hookBottom: "SCEGLI CON DATI VERI.",
    subline: "Where2Beach semplifica la decisione.",
    valueTitle: "PANORAMICA SMART",
    valueSub: "Stato attuale e trend in un colpo d'occhio.",
    ctaTitle: "Nuovo strumento in arrivo.",
    ctaLead: "ISCRIVITI ALLA LISTA D'ATTESA",
    ctaButton: "RICEVI L'ACCESSO",
    accent: "#0EA5E9",
    accentSoft: "rgba(14,165,233,0.28)",
    introStyle: 5,
    valueStyle: 1,
    ctaStyle: 2,
    hue: 16,
    saturation: 1.05,
    darkness: 0.54,
  },
  {
    id: "21",
    name: "Variazione 21",
    hookTop: "PARTI SOLO QUANDO CONVIENE.",
    hookBottom: "IL RADAR TI GUIDA.",
    subline: "Mappa aggiornata dalla community, sempre.",
    valueTitle: "VISIBILITA TOTALE",
    valueSub: "Dal pieno al libero, tutto subito chiaro.",
    ctaTitle: "Dai priorita alle giornate perfette.",
    ctaLead: "ENTRA NELLA WAITLIST",
    ctaButton: "UNISCITI ORA",
    accent: "#2DD4BF",
    accentSoft: "rgba(45,212,191,0.3)",
    introStyle: 1,
    valueStyle: 5,
    ctaStyle: 4,
    hue: -6,
    saturation: 1.12,
    darkness: 0.6,
  },
  {
    id: "22",
    name: "Variazione 22",
    hookTop: "NIENTE PIU TENTATIVI.",
    hookBottom: "SOLO SCELTE GIUSTE.",
    subline: "Apri, controlla, decidi in pochi istanti.",
    valueTitle: "REPORT UTILI ORA",
    valueSub: "Le zone vengono aggiornate durante la giornata.",
    ctaTitle: "Il lancio si avvicina.",
    ctaLead: "PRENOTA IL TUO POSTO",
    ctaButton: "ISCRIVITI SUBITO",
    accent: "#38BDF8",
    accentSoft: "rgba(56,189,248,0.29)",
    introStyle: 2,
    valueStyle: 1,
    ctaStyle: 5,
    hue: 24,
    saturation: 1.04,
    darkness: 0.52,
  },
  {
    id: "23",
    name: "Variazione 23",
    hookTop: "MENO TRAFFICO.",
    hookBottom: "PIU SPIAGGIA.",
    subline: "Dati semplici per scegliere meglio ogni giorno.",
    valueTitle: "SCANSIONE ISTANTANEA",
    valueSub: "Dove c'e posto, lo vedi subito.",
    ctaTitle: "Where2Beach e quasi live.",
    ctaLead: "ISCRIVITI PER PRIMO",
    ctaButton: "ENTRA ADESSO",
    accent: "#06B6D4",
    accentSoft: "rgba(6,182,212,0.3)",
    introStyle: 3,
    valueStyle: 2,
    ctaStyle: 1,
    hue: -14,
    saturation: 1.16,
    darkness: 0.62,
  },
  {
    id: "24",
    name: "Variazione 24",
    hookTop: "SCELTE RAPIDE.",
    hookBottom: "GIORNATE MIGLIORI.",
    subline: "Il radar legge la situazione per te.",
    valueTitle: "TRE LIVELLI, TUTTO CHIARO",
    valueSub: "Poco affollata, media, piena.",
    ctaTitle: "Sali a bordo prima del lancio.",
    ctaLead: "LASCIA LA TUA ISCRIZIONE",
    ctaButton: "VADO IN WAITLIST",
    accent: "#22D3EE",
    accentSoft: "rgba(34,211,238,0.28)",
    introStyle: 4,
    valueStyle: 3,
    ctaStyle: 2,
    hue: 2,
    saturation: 1.1,
    darkness: 0.57,
  },
  {
    id: "25",
    name: "Variazione 25",
    hookTop: "PRIMA CONTROLLA.",
    hookBottom: "POI GODITI IL MARE.",
    subline: "Riduci imprevisti e scegli la zona migliore.",
    valueTitle: "DECISIONE IN 10 SECONDI",
    valueSub: "Visuale completa con aggiornamenti continui.",
    ctaTitle: "Il nuovo radar sta arrivando.",
    ctaLead: "ISCRIVITI ORA ALLA LISTA",
    ctaButton: "RICEVI IL LINK",
    accent: "#0EA5E9",
    accentSoft: "rgba(14,165,233,0.3)",
    introStyle: 5,
    valueStyle: 4,
    ctaStyle: 3,
    hue: -20,
    saturation: 1.2,
    darkness: 0.64,
  },
  {
    id: "26",
    name: "Variazione 26",
    hookTop: "SCEGLI BENE.",
    hookBottom: "ARRIVA SERENO.",
    subline: "L'affollamento non e piu una sorpresa.",
    valueTitle: "DATI VIVI DALLA COMMUNITY",
    valueSub: "Le segnalazioni danno una marcia in piu.",
    ctaTitle: "Preparati all'estate smart.",
    ctaLead: "ENTRA NELLA WAITLIST OGGI",
    ctaButton: "ISCRIVIMI",
    accent: "#14B8A6",
    accentSoft: "rgba(20,184,166,0.3)",
    introStyle: 1,
    valueStyle: 3,
    ctaStyle: 5,
    hue: 12,
    saturation: 1.08,
    darkness: 0.56,
  },
  {
    id: "27",
    name: "Variazione 27",
    hookTop: "BLOCCA IL CAOS.",
    hookBottom: "APRITI IL MARE.",
    subline: "Confronta le aree e vai sul sicuro.",
    valueTitle: "MENO INDECISIONE",
    valueSub: "Il radar ti mostra subito cosa sta succedendo.",
    ctaTitle: "Where2Beach parte a breve.",
    ctaLead: "ACCEDI ALLA LISTA D'ATTESA",
    ctaButton: "MI UNISCO",
    accent: "#06B6D4",
    accentSoft: "rgba(6,182,212,0.29)",
    introStyle: 2,
    valueStyle: 4,
    ctaStyle: 1,
    hue: -8,
    saturation: 1.14,
    darkness: 0.61,
  },
  {
    id: "28",
    name: "Variazione 28",
    hookTop: "AGGIORNATA ORA.",
    hookBottom: "DECIDI ORA.",
    subline: "Dove c'e spazio lo sai in tempo reale.",
    valueTitle: "MAPPA SEMPRE ACCESA",
    valueSub: "Segnali continui per partenze intelligenti.",
    ctaTitle: "Nuova esperienza in arrivo.",
    ctaLead: "ISCRIVITI PER L'ACCESSO",
    ctaButton: "OTTIENI INVITO",
    accent: "#38BDF8",
    accentSoft: "rgba(56,189,248,0.28)",
    introStyle: 3,
    valueStyle: 5,
    ctaStyle: 2,
    hue: 18,
    saturation: 1.06,
    darkness: 0.55,
  },
  {
    id: "29",
    name: "Variazione 29",
    hookTop: "MENO RUMORE.",
    hookBottom: "PIU INFORMAZIONE.",
    subline: "Il radar filtra il caos e semplifica tutto.",
    valueTitle: "RISPOSTE SUBITO PRONTE",
    valueSub: "Apri la mappa e capisci dove andare.",
    ctaTitle: "Lancio imminente di Where2Beach.",
    ctaLead: "LASCIACI LA TUA EMAIL",
    ctaButton: "ISCRIVITI ALLA LISTA",
    accent: "#22D3EE",
    accentSoft: "rgba(34,211,238,0.29)",
    introStyle: 4,
    valueStyle: 1,
    ctaStyle: 4,
    hue: -4,
    saturation: 1.13,
    darkness: 0.6,
  },
  {
    id: "30",
    name: "Variazione 30",
    hookTop: "SE VEDI PRIMA.",
    hookBottom: "SCEGLI MEGLIO.",
    subline: "Dalla situazione attuale alla partenza migliore.",
    valueTitle: "VANTAGGIO REALE",
    valueSub: "Decidi prima degli altri e goditi la giornata.",
    ctaTitle: "Ultimi giorni prima dell'apertura.",
    ctaLead: "ENTRA ORA NELLA WAITLIST",
    ctaButton: "MI METTO IN CODA",
    accent: "#2DD4BF",
    accentSoft: "rgba(45,212,191,0.3)",
    introStyle: 5,
    valueStyle: 2,
    ctaStyle: 3,
    hue: 6,
    saturation: 1.09,
    darkness: 0.58,
  },
];
